color_theme = "/home/dich/.config/btop/themes/catppuccin_macchiato.theme"

truecolor = True
rounded_corners = True

shown_boxes = "proc mem cpu"
update_ms = 2000

proc_sorting = "cpu lazy"
proc_tree = True

mem_graphs = True
show_swap = True

show_cpu_freq = True
clock_format = "%X"

background_update = True

show_battery = True
