services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb-name
    ports:
      - "3306:3306"
    networks:
      - websecure
networks:
  websecure:
    external: true
