[Analyzer]
framerate=25
type=BlockAnalyzer

[Appearance]
style=default

[Backend]
output=autoaudiosink
playbin3=true
bufferduration=4000

[Behaviour]
language=zh_CN
seek_step_sec=10
showtrayicon=true
volume_increment=5

[Collection]
group_by1=1
group_by2=4

[Context]
AlbumEnable=true
SearchCoverEnable=true
SearchLyricsEnable=true
SongLyricsEnable=true

[Covers]
providers=Last.fm, MusicBrainz, Deezer, Musixmatch, OpenTidal, Tidal, Spotify, Qobuz

[Equalizer]
enabled=false

[GlobalShortcuts]
next_track=Media Next
play_pause=Media Play
prev_track=Media Previous
stop=Media Stop
use_kglobalaccel=true

[Lyrics]
providers=Lyrics.ovh, LoloLyrics, Musixmatch, songlyrics.com, azlyrics.com, elyrics.net, letras.mus.br, lyricfind.com

[MainWindow]
do_not_show_sponsor_message=true

[OSD]
ShowArt=true
Timeout=5000

[Player]
volume=100

[Playlist]
alternating_row_colors=true
show_toolbar=true
