set -g default-command 'pwsh.exe'
set -g mouse on
set -g base-index 1
set -g escape-time 0
set -g xterm-keys on
set -s extended-keys on
set -g focus-events on
set -g history-limit 10000
set -g default-terminal "xterm-256color"
set -g status-interval 1

set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
set -g status-left ""
set -g status-right "#[fg=#cba6f7,bg=#1e1e2e]#[bg=#cba6f7,fg=#11111b] #S #[fg=#cba6f7,bg=#1e1e2e]#[fg=#45475a,bg=#1e1e2e]#[bg=#45475a,fg=#cdd6f4] #H #[fg=#45475a,bg=#1e1e2e]#[fg=#a6e3a1,bg=#1e1e2e]#[bg=#a6e3a1,fg=#11111b] %H:%M #[fg=#a6e3a1,bg=#1e1e2e]"

set -g window-status-format "#[fg=#45475a,bg=#1e1e2e]#[bg=#45475a,fg=#bac2de] #I:#W #[fg=#45475a,bg=#1e1e2e]"
set -g window-status-current-format "#[fg=#cba6f7,bg=#1e1e2e]#[bg=#cba6f7,fg=#11111b,bold] #I:#W #[fg=#cba6f7,bg=#1e1e2e]"
set -g window-status-separator ""

set -g pane-active-border-style "fg=#cba6f7"
set -g pane-border-style "fg=#45475a"

set -g status-left-length 50
set -g status-right-length 150
